### ISSUE TITLE
Plugin creation issue collection

### ISSUE THREAD

**Issue by forrestfwilliams** [ASFHyP3/hyp3-cookiecutter#26]
This is an issue where I'm recording issues I ran into while using the version of the cookiecutter currently in `update-staging`. I'll expand this into more actionable issues if necessary.

**Comment by forrestfwilliams** [comment]
We don't mention that the values input while creating the repository should be the same as those input into the cookiecutter.

**Comment by forrestfwilliams** [comment]
conda env file is `environment.yml`, not `conda_env.yml`

**Comment by forrestfwilliams** [comment]
git init defaults to create a `master` branch, might want to make note about setting `git config --global init.defaultBranch main` to create a `main` branch instead.

**Comment by forrestfwilliams** [comment]
Git setup should be:

```bash
git init .
git remote add origin https://github.com/ASFHyP3/hyp3-isce2.git
git add .
git commit -m "Minimal HyP3 plugin created with the hyp3 plugin cookiecutter"
git branch -M main
git push -u origin main

git tag -a v0.0.0 -m "Marking zeroth release for auto-versioning and CI/CD Tooling"
git push --tags

git checkout -b develop
git push -u origin develop
```

**Comment by forrestfwilliams** [comment]
Pull Request (not Merge button) settings should look like this:

<img width="669" alt="Screen Shot 2023-03-23 at 3 11 51 PM" src="https://user-images.githubusercontent.com/31411324/227340995-79a42043-d067-45d8-9926-5098d3a95435.png">

**Comment by forrestfwilliams** [comment]
Make note about changing default branch to `develop`

**Comment by forrestfwilliams** [comment]
Develop branch rules:
<img width="397" alt="Screen Shot 2023-03-23 at 3 19 22 PM" src="https://user-images.githubusercontent.com/31411324/227343055-6d726e28-206e-4347-88ea-1120d784eeda.png">

<img width="403" alt="Screen Shot 2023-03-23 at 3 19 38 PM" src="https://user-images.githubusercontent.com/31411324/227343094-ebc08db7-73bf-4d61-a13a-830815fb343b.png">

**Comment by forrestfwilliams** [comment]
Change environment.yml python version to `python>=3.8`

**Comment by forrestfwilliams** [comment]
Will need to add back in science entry point

**Comment by forrestfwilliams** [comment]
Need to update dockerfile entrypoint to include `src` dir.

**Comment by forrestfwilliams** [comment]
Change checklist comment to:

```
name: Checklist comment

on:
  pull_request:
    types:
      - opened
    branches:
      - main
  
jobs:
  call-release-workflow:
    uses: ASFHyP3/actions/.github/workflows/reusable-release-checklist-comment.yml@v0.7.1
    permissions:
      pull-requests: write
    secrets:
      USER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
